---
- hosts: 127.0.0.1
  vars:
    http_port: 4568
    max_clients: 80
    createuser: 'ansibleremote'
    createpassword: 'myamazingpassword'
  remote_user: root
  tasks: 
    - user: name=johnd comment="John Doe" uid=1040
    - name: Create uwsgi directory in log
      file: path=/var/log/uwsgi state=directory
    - name: Create uwsgi directory in etc
      file: path=/etc/uwsgi state=directory
    - name: Create vassals directory in uwsgi
      file: path=/etc/uwsgi/vassals state=directory