---
- hosts: default
  user: vagrant
  sudo: yes
  tasks: 
    - name: Create admin system group
      group: name=admins system=yes state=present

    - name: Create administrator account
      user: name={{ lookup('env', 'USER') }} state=present shell=/bin/sh groups=admins

    - name: Install ssh public key from current account
      authorized_key: user={{ lookup('env','USER') }} key="{{ lookup('file','~/.ssh/id_rsa.pub') }}"

    - name: Configure admins group access in sudo
      lineinfile: "dest=/etc/sudoers.d/admins state=present create=yes regexp='^%admins' line='%admins ALL=(ALL:ALL) NOPASSWD: SETENV: ALL' owner=root group=root mode=0440"
    
    - name: update apt-get 
      apt: update_cache=yes

    - name: Install virtualenv 
      apt: name=python-virtualenv state=latest

    - name: Installs pip
      apt: name=python-pip state=latest

    - name: Load virtualenv into stenosaurus directory
      command: virtualenv /vagrant/stenosaurus/bin

    - name: Install pyramid and pyramid-make through virtualenv
      easy_install: name={{ item }} virtualenv=/vagrant/stenosaurus/bin
      with_items:
        - pyramid
        - pyramid-mako

    - name: install python-dev
      apt: name=python-dev

    - name: Installs nginx
      apt: name=nginx state=latest

    - name: Installs uwsgi
      command: pip install uwsgi

    - name: Create uwsgi directory in log
      file: path=/var/log/uwsgi state=directory

    - name: Create uwsgi directory in etc
      file: path=e/tc/uwsgi state=directory

    - name: Create vassals directory in uwsgi
      file: path=/etc/uwsgi/vassals state=directory

    - name: create log directory
      file: path=/var/sites/stenosaurus/log state=directory

    - name: make link between files create symoblic link for uwsgi.ini
      file: src=/var/sites/stenosaurus/config/uwsgi.ini dest=/etc/uwsgi/vassals/stenosaurus.ini state=link force=yes

    - name: make link between files and create symbolic link for nginx.config
      file: src=/var/sites/stenosaurus/config/nginx.conf dest=/etc/nginx/sites-enabled/stenosaurus state=link force=yes

    - name: create symbolic link to access the nginx access-log
      file: src=/var/log/nginx/access.log dest=/var/sites/stenosaurus/log/nginx_access.log state=link force=yes

    - name: Create emperor.ini
      copy: src=files/emporer.ini dest=/etc/uwsgi/emporor.ini 

    - name: create uwsgi.conf 
      copy: src=files/uwsgi.conf dest=/etc/init/uwsgi.conf

    - name: start uwsgi 
      command: initctl start uwsgi

    - name: nginx restart 
      command: service nginx restart