---
- hosts: default
  vars:
    http_port: 4568
    max_clients: 80
  user: vagrant
  sudo: yes
  tasks: 
    - name: Create admin system group
      group: name=admins system=yes state=present

    - name: Create administrator account
      user: name={{ lookup('env', 'USER') }} state=present shell=/bin/sh groups=admins

    - name: Install ssh public key from current account
      authorized_key: user={{ lookup('env','USER') }} key="{{ lookup('file','~/.ssh/id_rsa.pub') }}"

    - name: Configure admins group access in sudo
      lineinfile: "dest=/etc/sudoers.d/admins state=present create=yes regexp='^%admins' line='%admins ALL=(ALL:ALL) NOPASSWD: SETENV: ALL' owner=root group=root mode=0440"

    - name: Create uwsgi directory in log
      file: path=/var/log/uwsgi state=directory

    - name: Create uwsgi directory in etc
      file: path=/etc/uwsgi state=directory

    - name: Create vassals directory in uwsgi
      file: path=/etc/uwsgi/vassals state=directory