- name: Create admin system group
  group: name=admins system=yes state=present

- name: Create administrator account
  user: name={{ lookup('env', 'USER') }} state=present shell=/bin/sh groups=admins

- name: Install ssh public key from current account
  authorized_key: user={{ lookup('env','USER') }} key="{{ lookup('file','~/.ssh/id_rsa.pub') }}"

- name: Configure admins group access in sudo
  lineinfile: "dest=/etc/sudoers.d/admins state=present create=yes regexp='^%admins' line='%admins ALL=(ALL:ALL) NOPASSWD: SETENV: ALL' owner=root group=root mode=0440"
    